"use client";

import { useEffect, useState } from "react";
import { AlertCircle, KeyRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { authApi, AuthError } from "@/lib/api/auth";
import type { AdminPrincipal, TwoFactorEnrollment } from "@/types/admin";
import { CopyableId } from "@/components/admin/shared/detail";
import { OtpField } from "./otp-field";

/**
 * TOTP enrolment: POST /auth/admin/2fa/enable (QR + secret) then
 * /auth/admin/2fa/confirm with a code. Works with the login setup token or
 * the current session (handled by the BFF).
 */
export function TwoFactorSetup({
  onComplete,
  onCancel,
}: {
  onComplete: (user: AdminPrincipal | null) => void;
  onCancel?: () => void;
}) {
  const [enrollment, setEnrollment] = useState<TwoFactorEnrollment | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  const [attempt, setAttempt] = useState(0);

  useEffect(() => {
    let cancelled = false;
    authApi
      .enable2fa()
      .then((data) => !cancelled && setEnrollment(data))
      .catch((e: AuthError) => !cancelled && setLoadError(e.message));
    return () => {
      cancelled = true;
    };
  }, [attempt]);

  const confirm = async (token: string) => {
    if (token.length !== 6 || pending) return;
    setPending(true);
    setError(null);
    try {
      const result = await authApi.confirm2fa(token);
      onComplete(result.status === "authenticated" ? result.user : null);
    } catch (e) {
      setError((e as AuthError).message);
      setCode("");
    } finally {
      setPending(false);
    }
  };

  if (loadError) {
    return (
      <div className="space-y-4">
        <p role="alert" className="flex items-start gap-2 rounded-lg border border-destructive-border bg-destructive-soft px-3 py-2.5 text-sm text-destructive">
          <AlertCircle className="mt-0.5 size-4 shrink-0" />
          {loadError}
        </p>
        <div className="flex gap-2">
          {onCancel && (
            <Button variant="outline" onClick={onCancel}>
              Back
            </Button>
          )}
          <Button
            onClick={() => {
              setLoadError(null);
              setAttempt((n) => n + 1);
            }}
          >
            Try again
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <ol className="space-y-4 text-sm">
        <li className="space-y-3">
          <p className="font-medium">1. Scan this QR code with your authenticator app</p>
          <div className="flex flex-col items-center gap-3 rounded-lg border bg-muted/40 p-4 sm:flex-row sm:items-start">
            {enrollment ? (
              // Data URL generated by the backend (qrcode.toDataURL); not a remote image.
              // eslint-disable-next-line @next/next/no-img-element
              <img src={enrollment.qr_code} alt="Two-factor authentication QR code" className="size-36 rounded-md border bg-white p-1.5" />
            ) : (
              <Skeleton className="size-36" />
            )}
            <div className="min-w-0 space-y-1.5 text-center sm:text-left">
              <p className="flex items-center justify-center gap-1.5 text-xs text-muted-foreground sm:justify-start">
                <KeyRound className="size-3.5" /> Or enter this key manually
              </p>
              {enrollment ? <CopyableId value={enrollment.secret} /> : <Skeleton className="h-4 w-40" />}
            </div>
          </div>
        </li>
        <li className="space-y-3">
          <p className="font-medium">2. Enter the 6-digit code it shows</p>
          <OtpField value={code} onChange={setCode} onComplete={confirm} disabled={!enrollment || pending} />
        </li>
      </ol>
      {error && (
        <p role="alert" className="text-center text-sm text-destructive">
          {error}
        </p>
      )}
      <div className="flex gap-2">
        {onCancel && (
          <Button variant="outline" onClick={onCancel} disabled={pending} className="flex-1">
            Cancel
          </Button>
        )}
        <Button onClick={() => confirm(code)} loading={pending} disabled={code.length !== 6 || !enrollment} className="flex-1">
          Enable two-factor
        </Button>
      </div>
    </div>
  );
}
